FROM node:14.19.0
WORKDIR /usr/cloud-apps/ui
COPY ./package.json ./

## WAIT mod
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

RUN npm install
