# Stage 1 - build process
FROM  node:13.12.0-alpine3.10 as builder

WORKDIR /usr/cloud-apps/ui

COPY ./package.json ./

RUN npm install

COPY . ./

RUN npm run build

# Stage 2 - prod env
FROM nginx
EXPOSE 3000
COPY --from=builder /usr/cloud-apps/ui/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
