version: '3'
services:
  ui:
    container_name: ui_dev
    working_dir: /usr/create-app/ui
    environment:
      - DOCKER_VARIANT=nginx_routing
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/usr/create-app/ui
      - /usr/create-app/ui/node_modules
    command: |
      sh -c "npm run start"
  api:
    container_name: api_dev
    working_dir: /usr/create-app/api
    environment:
      - DOCKER_VARIANT=nginx_routing
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
    - ./api:/usr/create-app/api
    - /usr/create-app/api/node_modules
    command: |
      sh -c "npm run dev"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '5000:80'