version: '3'
services:
  ui:
    container_name: ui_dev
    working_dir: /usr/create-app/ui
    ports:
    - "3000:3000"
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/usr/create-app/ui
      - /usr/create-app/ui/node_modules
    command: |
      sh -c "npm run start"
  api:
    container_name: api_dev
    working_dir: /usr/create-app/api
    ports:
    - "4000:4000"
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
    - ./api:/usr/create-app/api
    - /usr/create-app/api/node_modules
    command: |
      sh -c "npm run dev"