version: '3'
services:
  postgres:
    container_name: pgdb_dev
    build:
      context: ./pgdb
      dockerfile: Dockerfile.dev
    ports:
      - "5432:5432"
  api:
    container_name: api_dev
    working_dir: /usr/create-app/api
    environment:
      - DOCKER_VARIANT=compose_routing
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - WAIT_HOSTS=postgres:5432
    ports:
    - "4000:4000"
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
    - ./api:/usr/create-app/api
    - /usr/create-app/api/node_modules
    command: |
      sh -c "/wait && npm run dev"
  ui:
    container_name: ui_dev
    working_dir: /usr/create-app/ui
    environment:
      - DOCKER_VARIANT=compose_routing
      - WAIT_HOSTS=api:4000
    ports:
    - "3000:3000"
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/usr/create-app/ui
      - /usr/create-app/ui/node_modules
    command: |
      sh -c "/wait && npm run start"
