api:
  environment:
    PGDATABASE: postgres
    PGHOST: postgres
    PGPASSWORD: postgres_password
    PGPORT: '5432'
    PGUSER: postgres
  image: "${DB_IMAGE}"
  links:
  - postgres:postgres
  ports:
  - 4000:4000
postgres:
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
  image: "${API_IMAGE}"
  ports:
  - 5432:5432
ui:
  image: "${UI_IMAGE}"
  links:
  - api:api
  ports:
  - 80:3000
