api:
  environment:
    PGDATABASE: postgres
    PGHOST: postgres
    PGPASSWORD: postgres_password
    PGPORT: '5432'
    PGUSER: postgres
  image: "621650508462.dkr.ecr.ca-central-1.amazonaws.com/api_dev:v1.0.2"
  links:
  - postgres:postgres
  ports:
  - 4000:4000
postgres:
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust
  image: "621650508462.dkr.ecr.ca-central-1.amazonaws.com/postgres_dev:v1.0.2"
  ports:
  - 5432:5432
ui:
  image: "621650508462.dkr.ecr.ca-central-1.amazonaws.com/ui_dev:v1.0.2"
  links:
  - api:api
  ports:
  - 80:3000
