version: '3'
services:
  postgres:
    container_name: postgres_dev
    image:  "621650508462.dkr.ecr.ca-central-1.amazonaws.com/postgres_dev:v1.0.0"
    ports:
      - "5432:5432"
    # TODO - replace this by creating a default superadmin with SQL for phase 4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    container_name: api_dev
    working_dir: /usr/cloud-apps/api
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - WAIT_HOSTS=postgres:5432
    ports:
      - "4000:4000"
    depends_on:
      - postgres

    image:  621650508462.dkr.ecr.ca-central-1.amazonaws.com/api_dev:v1.0.0
    command: |
      sh -c "/wait && npm run dev"
  ui:
    container_name: ui_dev
    working_dir: /usr/cloud-apps/ui
    environment:
      - WAIT_HOSTS=api:4000
    ports:
      - "3000:3000"
    image:  621650508462.dkr.ecr.ca-central-1.amazonaws.com/ui_dev:v1.0.0
    volumes:
      - ./client/ui:/usr/cloud-apps/ui
      - /usr/cloud-apps/ui/node_modules
    command: |
      sh -c "/wait && npm run dev"
    depends_on:
      - postgres
      - api
