version: '3'
services:
  hub:
    image: selenium/hub:3.0.1
    networks:
      - nightwatch-docker-grid-network
    environment:
      GRID_BROWSER_TIMEOUT: 120000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 8000
      GRID_NODE_POLLING: 300
      GRID_TIMEOUT: 120000
    ports:
      - '4444:4444'
  node-chrome:
    image: selenium/node-chrome:3.0.1
    networks:
      - nightwatch-docker-grid-network
    environment: &SELENIUM_NODE_ENV
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
    logging:
      driver: none
  ui:
    container_name: ui
    working_dir: /usr/cloud-apps/ui
    networks:
      - nightwatch-docker-grid-network
    ports:
      - "3000:3000"
    build:
      context: ./client/ui
      dockerfile: docker/Dockerfile.test
    command: |
      sh -c "npm run start"
  e2e:
    container_name: e2e
    working_dir: /usr/cloud-apps/e2e
    networks:
      - nightwatch-docker-grid-network
    environment:
      - UI_HOST=ui
      - UI_PORT=3000
      - SELENIUM_PORT=4444
      - SELENIUM_HOST=chromedriver
      - SELENIUM_HUB=hub
      - DOCKER=true
      - WAIT_HOSTS= ui:3000
    build:
      context: ./client/tests
      dockerfile: docker/Dockerfile
    command: |
      sh -c "/wait && sleep 10 && npm start smoke sad"
networks:
  nightwatch-docker-grid-network:
    driver: bridge
