version: '3'
services:
  ui:
    container_name: ui_prod
    working_dir: /usr/create-app/ui
    environment:
      - DOCKER_VARIANT=compose_routing
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    volumes:
      - ./ui:/usr/create-app/ui
      - /usr/create-app/ui/node_modules
    ports:
      - '3000:80'
  api:
    container_name: api_prod
    working_dir: /usr/create-app/api
    environment:
      - DOCKER_VARIANT=compose_routing
    ports:
    - "4000:4000"
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    volumes:
    - ./api:/usr/create-app/api
    - /usr/create-app/api/node_modules