# Workaround - node alpine throwing weird error w/ sequelize postgres
FROM node:13.12.0-alpine3.10
WORKDIR /usr/cloud-apps/api

COPY ./package.json ./

RUN npm install

COPY ./ ./

## WAIT mod
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

