branch-defaults:
  feature/demo:
    environment: cloudapps-dev
environment-defaults:
  cloudapps-dev:
    branch: null
    repository: null
global:
  application_name: cloud-apps
  environment: cloudapps-dev
  default_ec2_keyname: null
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
