branch-defaults:
  feature/multicontainer_deployment:
    environment: cloud-apps-dev
    group_suffix: null
global:
  application_name: cloud-apps
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
