branch-defaults:
  feature/ci_cd_pipeline:
    environment: Cloudapps-env
    group_suffix: null
environment-defaults:
  Cloudapps-env:
    branch: null
    repository: null
global:
  application_name: cloud-apps
  branch: null
  default_ec2_keyname: null
  default_platform: Multi-container Docker running on 64bit Amazon Linux
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
