version: '3'
services:
  api:
    container_name: api_test
    working_dir: /usr/create-app/api
    ports:
      - "4000:4000"
    build:
      context: ../api
      dockerfile: ../api/docker/Dockerfile.dev
    volumes:
      - ../api:/usr/create-app/api
      - /usr/create-app/api/node_modules
    command: |
      sh -c "npm run test"