version: '3'
services:
  ui:
    container_name: ui_dev
    working_dir: /usr/create-app/ui
    environment:
      - REACT_APP_environment=docker_dev
      - DOCKER_VARIANT=compose_routing
    ports:
    - "3000:3000"
    build:
      context: ../ui
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../ui:/usr/create-app/ui
      - /usr/create-app/ui/node_modules
    command: |
      sh -c "/wait && npm run start"
