version: '3'
services:
  postgres:
    container_name: pgdb_dev
    build:
      context: ../db
      dockerfile: ../db/Dockerfile.dev
    ports:
      - "5432:5432"
  ui:
    container_name: ui_prod
    working_dir: /usr/create-app/ui
    environment:
      - DOCKER_VARIANT=compose_routing
      - REACT_APP_DOCKER_VARIANT=nginx_routing
    build:
      context: ../ui
      dockerfile: ../ui/Dockerfile.prod
    ports:
      - "3000:3000"
  api:
    container_name: api_prod
    working_dir: /usr/create-app/api
    environment:
      - DOCKER_VARIANT=nginx_routing
      - REACT_APP_DOCKER_VARIANT=nginx_routing
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
    - "4000:4000"
    build:
      context: ../api
      dockerfile: api/ops/Dockerfile
  nginx:
    restart: always
    build:
      dockerfile: ../nginx/Dockerfile.prod
      context: ../nginx
    ports:
      - '5000:5000'