version: '3'
# TODO - clean up ports for ui / api / postgres - likely unecessary
services:
  ## TODO - remove this for no-data version
  postgres:
    container_name: pgdb_test
    build:
      context: ../db
    ports:
      - "5432:5432"
    # TODO - replace this by creating a default superadmin with SQL for phase 4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  ## TODO replace this with prod API when issue #97 is addressed
  api:
    container_name: api_test
    working_dir: /usr/create-app/api
    environment:
      - DOCKER_VARIANT=compose_routing
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - WAIT_HOSTS=postgres:5432
    ports:
      - "4000:4000"
    build:
      context: ../api
      dockerfile: ops/Dockerfile.dev
    volumes:
      - ../api:/usr/create-app/api
      - /usr/create-app/api/node_modules
    command: |
      sh -c "/wait && npm start"
  ## TODO replace this with prod UI when issue #97 is addressed
  ui:
    container_name: ui_test
    working_dir: /usr/create-app/ui
    environment:
      - REACT_APP_environment=docker_dev
      - DOCKER_VARIANT=compose_routing
      - WAIT_HOSTS=api:4000
    ports:
      - "3000:3000"
    build:
      context: ../ui
      dockerfile: Dockerfile.dev
    volumes:
      - ../ui:/usr/create-app/ui
      - /usr/create-app/ui/node_modules
    command: |
      sh -c "/wait && npm run start"
  ## TODO - add ngnix routing to job when prod for UI is fixed
  chromedriver:
    container_name: chromedriver
    image: selenium/standalone-chrome:latest
  e2e:
    container_name: e2e_test
    working_dir: /usr/create-app/e2e
    environment:
      - UI_HOST=ui
      - UI_PORT=3000
      - SELENIUM_PORT=4444
      - SELENIUM_HOST=chromedriver
      - WAIT_HOSTS=chromedriver:4444, ui:3000
      - WAIT_AFTER_HOSTS=10
    build:
      context: ../e2e
      dockerfile: ops/Dockerfile
    volumes:
      - ../e2e:/usr/create-app/e2e
      - /usr/create-app/e2e/node_modules
    command: |
      sh -c "/wait && npm run test-docker"