version: '3'
services:
  postgres:
    container_name: pgdb_test
    build:
      context: ../db
    ports:
      - "5432:5432"
    # TODO - replace this by creating a default superadmin with SQL for phase 4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    container_name: api_test
    working_dir: /usr/create-app/api
    environment:
      - DOCKER_VARIANT=compose_routing
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - WAIT_HOSTS=postgres:5432
    ports:
      - "4000:4000"
    build:
      context: ../api
      dockerfile: ops/Dockerfile.dev
    volumes:
      - ../api:/usr/create-app/api
      - /usr/create-app/api/node_modules
    command: |
      sh -c "/wait && npm run dev"
  ui:
    container_name: ui_test
    working_dir: /usr/create-app/ui
    environment:
      - REACT_APP_environment=docker_dev
      - DOCKER_VARIANT=compose_routing
      - WAIT_HOSTS=api:4000
    ports:
      - "3000:3000"
    build:
      context: ../ui
      dockerfile: Dockerfile.dev
    volumes:
      - ../ui:/usr/create-app/ui
      - /usr/create-app/ui/node_modules
    command: |
      sh -c "/wait && npm run start"
  e2e:
    container_name: e2e_test
    working_dir: /usr/create-app/e2e
      - DOCKER_VARIANT=compose_routing
      - WAIT_HOSTS=ui:3000
    ports:
      - "3000:3000"
    build:
      context: ../e2e
      dockerfile: ops/Dockerfile.test
    volumes:
      - ../e2e:/usr/create-app/e2e
      - /usr/create-app/e2e/node_modules
    command: |
      sh -c "/wait && npm run test"
