
# Stage 1 - build process
FROM node:alpine as builder

WORKDIR /usr/create-app/ui

COPY ./package.json .
COPY ./src ./src
COPY ./scripts ./scripts
COPY ./config ./config
COPY ./public ./public

RUN npm install

RUN npm run build

# Stage 2 - prod env
FROM nginx
EXPOSE 3000
COPY --from=builder /usr/create-app/ui/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
