
# Stage 1 - build process
FROM node:alpine as builder

WORKDIR /usr/create-dapp/ui

COPY ./package.json .
COPY ./src ./src
COPY ./scripts ./scripts
COPY ./config ./config
COPY ./public ./public

RUN npm install

RUN npm run build

# Stage 2 - prod env
FROM nginx:alpine

ENV DOCKER prod

COPY --from=builder /usr/create-dapp/ui/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
