
# Stage 1 - build process
FROM node:alpine as builder

WORKDIR /usr/create-app/ui

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# Stage 2 - prod env
FROM nginx:alpine

ENV DOCKER prod

COPY --from=builder /usr/create-app/ui/build /usr/create-app/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
